### ISSUE TITLE
AlfCard Blog Post

### ISSUE THREAD

**Issue by TourDeRyan** [ClipCard/AlfCard#1]
Let's write a post for our blog about this

**Comment by eyelidlessness** [comment]
![image](https://cloud.githubusercontent.com/assets/199830/6363867/69dc29cc-bc53-11e4-9f10-154cb0102737.png)

**Comment by TourDeRyan** [comment]
[Posted!](http://clipcard.tumblr.com/post/112003917239/introducing-alfcard-instant-cloud-search-from)
